version: "3.9"

services:

  server:
    image: "spetr/icewarp:latest"
    container_name: "icewarp"
    platform: linux/amd64
    deploy:
      restart_policy:
        condition: on-failure
#    build:
#      context: ./server
#      dockerfile: Dockerfile
    secrets:
      - sql_password
    environment:
      SQL_HOST: "icewarp_sql"
      SQL_USER: "root"
      #SQL_PASSWORD: "dI9aK0bS2lX2nD5b"
      SQL_PASSWORD_FILE: "/run/secrets/sql_password"
      REDIS_HOST: "icewarp_redis"
    depends_on: 
      - icewarp_sql
    volumes:
      - type: "bind"
        source: "./data/icewarp"
        target: "/data"
    ports:
      - "25:25/tcp"     # SMTP
      - "80:80/tcp"     # HTTP
      - "8080:80/tcp"   # Alternative HTTP
      - "110:110/tcp"   # POP3
      - "143:143/tcp"   # IMAP
      - "443:443/tcp"   # HTTPS
      - "465:465/tcp"   # SMTPS
      - "587:587/tcp"   # SMTP
      - "993:993/tcp"   # IMAPS
      - "995:995/tcp"   # POP3S
      - "1080:1080/tcp" # SOCKS
      - "5060:5060/udp" # SIP
      - "5060:5060/tcp" # SIP
      - "5061:5061/udp" # SIP
      - "5222:5222/tcp" # XMLL
      - "5223:5223/tcp" # XMPP TLS
      - "5269:5269/tcp" # Groupware
    networks:
      - default

  icewarp_sql:
    image: "mariadb:latest"
    container_name: "icewarp_sql"
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - sql_password  
    environment:
      #MYSQL_ROOT_PASSWORD: "dI9aK0bS2lX2nD5b"
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/sql_password"
    volumes:
      - type: "bind"
        source: "./data/icewarp_sql"
        target: "/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - default

  icewarp_redis:
    image: "redis:latest"
    container_name: "icewarp_redis"
    deploy:
      restart_policy:
        condition: on-failure
    command: "--appendonly yes"
    volumes:
      - type: bind
        source: "./data/icewarp_redis"
        target: "/data"
    networks:
      - default

secrets:
  sql_password:
    file: ./secrets/sql_password.txt
