version: "3.9"
services:
  server:
    image: "spetr/icewarp:latest"
    container_name: "icewarp"
    build:
      context: server/.
      dockerfile: Dockerfile
    environment:
      DB_HOST: "mariadb"
      DB_USER: "root"
      DB_PASSWORD: "dI9aK0bS2lX2nD5b"
    depends_on: 
      - mariadb
    volumes:
      - type: bind
        source: ./data/icewarp
        target: /data
    ports:
      - "8080:80"
    networks:
      - default
  mariadb:
    image: "mariadb:latest"
    container_name: "icewarp_sql"
    environment:
      MYSQL_ROOT_PASSWORD: "dI9aK0bS2lX2nD5b"
    volumes:
      - type: bind
        source: ./data/icewarp_sql
        target: /var/lib/mysql
    ports:
      - "3309:3309"
    networks:
      - default
